### ISSUE TITLE
"fields.flat is not a function" logs to the console when commands that embed are triggered, and no response is sent

### ISSUE THREAD

**Issue by 69AR** [RagnarLothbrok-Odin/TheSeer-Discord#12]

**Comment by RagnarLothbrok-Odin** [comment]
Could you try updating your Node.js version?
Discord.js V12 requires at the minimum version 12 of node.
Let me know if that fixed it for you.

**Comment by RagnarLothbrok-Odin** [comment]
Feel free to reopen if the issue persists.
